name: animated_mesh_gradient
description: Animated Mesh Gradient is an eye-catching widget that renders an animated mesh gradient with a beautiful blurry effect between four user-defined colors. It can be used in Flutter applications to create stunning and dynamic user interfaces.
version: 1.0.1
repository: https://github.com/ben-fornefeld/animated_mesh_gradient

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_shaders: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  shaders:
    - packages/animated_mesh_gradient/shaders/mesh_gradient.frag

platforms:
  android:
  ios:
  web:
  macos:
  windows:
  linux:
